#!/bin/bash
#BATCH -J PartProdHello
#SBATCH --ntasks 16
#SBATCH --nodes 4
#SBATCH --tasks-per-node 4
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partedui


cd $SLURM_SUBMIT_DIR


mpirun -np 16 ./Sum

