#!/bin/bash
#SBATCH -J PartProdHello
#SBATCH --ntasks 10
#SBATCH --nodes 5
#SBATCH --tasks-per-node 2
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partedui


cd $SLURM_SUBMIT_DIR


mpirun -np 10 ./SumNonBlock
~                            